Repository casweeney/resolver, pull requests merged in 2024-04, with the labels that each got.

#15 added vue.js support & updated readme
  README.md
  src/lib.rs
  src/utils/command_arguments.rs
  src/utils/helpers.rs
Labels: documentation, enhancement

#16 Support for Vite added
  README.md
  src/lib.rs
  src/utils/command_arguments.rs
  src/utils/helpers.rs
Labels: documentation, enhancement

#17 Starkli installation implemented
  src/lib.rs
  src/utils/command_arguments.rs
  src/utils/helpers.rs
Labels: enhancement

#20 Fix noir/nargo installation
  src/utils/helpers.rs
Labels: enhancement, fixes

#21 Fix terminal reopening issue
  src/utils/helpers.rs
Labels: enhancement, fixes

#22 Scaffold Noir projects using resolver
  src/lib.rs
  src/utils/command_arguments.rs
  src/utils/helpers.rs
Labels: enhancement

#23 Feat/starknet foundry
  README.md
  src/lib.rs
  src/utils/command_arguments.rs
  src/utils/helpers.rs
Labels: enhancement, fixes

#24 Removed unused comments
  src/lib.rs
Labels: enhancement, fixes
